export const expStyle = {
    container : {
        backgroundColor: 'rgb(255, 255, 255)',
        color: 'rgb(97, 97, 97)',
        // transition: 'boxShadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
        borderRadius: '12px',
        overflow: 'hidden',
        // border: '1px solid rgba(144, 202, 249, 0.46)',
        boxShadow: 'none !important',
        height: 'max-content',
        padding:'30px',
        '& .MuiOutlinedInput-notchedOutline': {
            border: '1px solid #b97df0',
        },
    },
    subContainer : {
        bgcolor: '#fff',
        height: 'max-content',
        borderLeft: '0px',
        borderRight: '0px', 
        borderBottom: '0px', 
        borderRadius: '5px', 
        boxShadow: '6px 6px 6px 9px #dedbdbae', 
        margin: '20px',
    },
    buttonAdd: {
        backgroundColor: '#7009ab !important',
        color: 'white',
        textTransform: 'Capitalize',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover': {
            backgroundColor: '#9f3ed7 !important',
        }
    },
    exportBtnText : {
        backgroundColor: '#FBF2FF !important',
        color: '#7009AB !important',
        margin: '1px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        fontSize: '12px !important',
        borderRadius:" 3px !important",
        padding: "0",
        border:"1px solid #ddd !important",
        textTransform:'Capitalize',
    },
    buttonEdit : {
        backgroundColor: '#1572e8 !important',
        borderColor: '#1367d1 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    buttonView : {
        background: '#11cdef !important',
        borderColor: '#0fb9d8 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    buttonDelete : {
        background: '#f5365c !important',
        borderColor: '#f41e48 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    gridContainer : {
        marginTop: '50px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
    tableHead : {
        backgroundColor:"#f9f9f9 !important",
        color:'#525f7f !important',
        fontWeight:'bold !important',
        fontSize:'15px',
    },
    UnitHeaderText:{
        fontFamily:"'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif",
        fontSize: "23px",
        fontWeight: "400",
        margin:"10px 0px 10px 0px",
        color: 'rgb(94, 53, 177) !important',
    },
    UnitSubHeaderText:{
        fontSize: "15px",
        display: "inline-block",
        paddingLeft: "4px",
        fontWeight: "300",
        lineHeight: "1",
        color: 'rgb(94, 53, 177) !important',
    },
    boxheadertxt:{
        fontFamily: "'Source Sans Pro',sans-serif",
        fontSize: "18px",
        margin: "0",
        lineHeight: "1",
        color:" #32325d !important",
    },
    tablecontainer:{
        boxShadow:'none !important',
    },
    textInput : {
        padding: '20px',
        '& .MuiOutlinedInput-notchedOutline': {
            border: '1px solid #b97df0',
        },
    },
    spanIcons : {
        fontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    uploadBtn : {
        border:'1px solid #b97df0 !important',
        borderRadius: '7px !important',
        width: '159px !important',
        fontSize: '11px !important',
        color: '#7009ab !important',
        fontWeight: '600 !important',
            '&:hover' : {
                backgroundColor: '#7009ab !important',
                color: '#fff !important',
            },
    },

}