export const commonstyle = {
    container : {
        bgcolor: '#fff', 
        height: 'max-content', 
        borderTop: '5px solid #7009ab;', 
        borderLeft: '0px',
        borderRight: '0px', 
        borderBottom: '0px',
        borderRadius: '10px', 
        boxShadow: '6px 6px 6px 9px #dedbdbae',
    },
    sub_container : {
        bgcolor: '#fff',
        height: 'auto',
        borderLeft: '0px', 
        paddingTop: '10px',
        borderRight: '0px', 
        borderBottom: '0px', 
        borderRadius: '5px', 
        boxShadow: '6px 6px 6px 9px #dedbdbae', 
        marginTop: '50px',
    },
    button_add: {
        backgroundColor: '#7009ab !important',
        color: '#fff',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover' : {
            backgroundColor: '#fff !important',
            border: '1px solid #7009ab !important',
            color: '#7009ab ',
        }
    },
    button_grp : {
        backgroundColor: '#FBF2FF !important',
        color: '#7009AB !important',
        borderColor: '#ddd !important',
        margin: '1px !important',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        fontSize: '12px !important',
    },
    button_edit : {
        backgroundColor: '#1572e8 !important',
        borderColor: '#1367d1 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    button_view : {
        background: '#11cdef !important',
        borderColor: '#0fb9d8 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    button_delete : {
        background: '#f5365c !important',
        borderColor: '#f41e48 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
    },
    grid_container : {
        marginTop: '50px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
    button_linkadd : {
        textDecoration: 'none',
            color:'#fff',
        '&:hover' : {
            color: '#7009ab !important',
        }
    },

    
   

}