export const sellStyle = {
    container : {
        bgcolor: '#fff',
        height: 'max-content',
        borderTop: '5px solid #7009AB;',
        borderRadius: '10px',
        margin:'20px',
        padding:'30px',
        boxShadow: '6px 6px 6px 9px #dedbdbae',
    },
    subContainer : {
        bgcolor: '#fff',
        height: 'max-content',
        borderLeft: '0px',
        borderRight: '0px', 
        borderBottom: '0px', 
        borderRadius: '5px', 
        boxShadow: '6px 6px 6px 9px #dedbdbae', 
        margin: '20px',
    },
    buttonAdd: {
        backgroundColor: '#7009ab !important',
        color: 'white !important',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover' : {
            backgroundColor: '#fff !important',
            border: '1px solid #7009ab !important',
            color: '#a5becc !important',
        },
    },
    exportBtnText : {
        backgroundColor: '#FBF2FF !important',
        color: '#7009AB !important',
        margin: '1px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        fontSize: '12px !important',
        borderRadius:" 3px !important",
        padding: "0",
        border:"1px solid #ddd !important",
        textTransform:'Capitalize',
    },
    buttonEdit : {
        backgroundColor: '#1572e8 !important',
        borderColor: '#1367d1 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    buttonView : {
        background: '#11cdef !important',
        borderColor: '#0fb9d8 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    buttonDelete : {
        background: '#f5365c !important',
        borderColor: '#f41e48 !important',
        color: '#fff !important',
        margin: '1px !important',
        marginRight: '5px !important',
        alignItems: 'center !important',
        textAlign: 'center !important',
        justifyContent: 'center !important',
        height: '30px !important',
        fontSize: '12px !important',
        fontWeight: '750 !important',
        textTransform: 'Capitalize',
    },
    gridContainer : {
        marginTop: '50px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
    tableHead : {
        backgroundColor:"#f9f9f9 !important",
        color:'#525f7f !important',
        fontWeight:'bold !important',
        fontSize:'15px',
    },
    filterHead : {
        color: '#7009ab',
    },
    UnitHeaderText:{
        fontFamily:"'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif",
        fontSize: "23px",
        fontWeight: "400",
        margin:"10px 30px",
        color: "#384460 !important",
    },
    UnitSubHeaderText:{
        fontSize: "15px",
        display: "inline-block",
        paddingLeft: "4px",
        fontWeight: "300",
        lineHeight: "1",
        color: "#777",
    },
    boxheadertxt:{
        fontFamily: "'Source Sans Pro',sans-serif",
        fontSize: "18px",
        margin: "0",
        lineHeight: "1",
        color:" #32325d !important",
    },
    tablecontainer:{
        boxShadow:'none !important',
    },
    ImportContainer:{
        backgroundColor:'white !important',
        borderTop: '5px solid #7009AB;',
        height:'max-content',
        borderRadius:'5px',
        padding:'30px',
        margin:'0px 20px',
        boxShadow: '6px 6px 6px 9px #dedbdbae',
    },
    importheadtext:{
        fontSize:'20px !important',
    },
    importsubheadtext:{
        margin:'0',
    },
    importTabledata:{
        fontSize: '14px',
        color: '#0b1e4c !important',
    },
    importTableBoldText:{
        fontSize: 'small',
        fontWeight: 'bolder',
    },
    textInput : {
        padding: '20px',
        '& .MuiOutlinedInput-notchedOutline': {
            border: '1px solid #b97df0',
        },
    },
    actionsdropdown:{
        backgroundColor:"#b97df0",
        fontSize: 11,
        "&:hover":{
            backgroundColor: "#fff",
            color: "#b97df0"
        }
    },
    buttonPaid : {
        backgroundColor: '#98D973 !important',
        color: '#fff !important',
        height: '25px !important',
    },
    spanInfoIcons : {
        fontSize: '16px', 
        paddingTop: '0px !important', 
        paddingLeft: '1px',
        paddingRight: '2px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px !important', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanIcons : {
        fontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanLoc : {
        ontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '6px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    uploadBtn : {
        border:'1px solid #b97df0 !important',
        borderRadius: '7px !important',
        width: '159px !important',
        fontSize: '11px !important',
        color: '#7009ab !important',
        fontWeight: '600 !important',
            '&:hover' : {
                backgroundColor: '#7009ab !important',
                color: '#fff !important',
            },
    },
    tableHd : {
        backgroundColor: '#7009ab !important',
        fontSize: '20px !important',
        color: '#fff !important',
    },
    btnExpress : {
        backgroundColor: ' #605ca8',
        color:'white',
        fontSize: '11px',
        fontWeight: 'bold',
    },
    btnPause : {
        backgroundColor: '#ffad46',
        color: 'white',
        marginLeft: '5px',
    },
    btnMax : {
        backgroundColor:'#337ab7',
        color: 'white',
        marginLeft: '5px',
    },
    btnCal : {
        backgroundColor: '#5cb85c',
        color: 'white',
        marginLeft: '5px',
    },
    btnClose : {
        backgroundColor: '#d9534f',
        color: 'white',
        marginLeft: '5px',
    },
    btnBack : {
        backgroundColor: '#31b0d5',
        color: 'white',
        marginLeft: '5px',
    },
    imgBox : {
        backgroundColor:'white',
        width: '150px',
        height:'125px',
        justifyContent:'center',
        textAlign: 'center',
        padding: '5px',
    }
}