export const purchaseStyle = {
    container : {
        bgcolor: '#fff',
        height: 'max-content',
        borderTop: '5px solid #7009AB;',
        borderRadius: '10px',
        margin:'20px',
        padding:'30px',
        // boxShadow: '6px 6px 6px 9px #dedbdbae',
    },
    subContainer : {
        bgcolor: '#fff',
        height: 'max-content',
        borderLeft: '0px',
        borderRight: '0px', 
        borderBottom: '0px', 
        borderRadius: '5px', 
        // boxShadow: '6px 6px 6px 9px #dedbdbae', 
        margin: '20px',
    },
    buttonAdd: {
        backgroundColor: '#7009ab !important',
        color: 'white !important',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover' : {
            backgroundColor: '#fff !important',
            border: '1px solid #7009ab !important',
            color: '#a5becc !important',
        },
    },
    gridContainer : {
        marginTop: '10px', 
        marginBottom: '20px',
        justifyContent: 'center',
    },
    tableHead : {
        backgroundColor:"#f9f9f9 !important",
        color:'#525f7f !important',
        fontWeight:'bold !important',
        fontSize:'15px',
    },
    tableHead1 : {
        // backgroundColor:"#f9f9f9 !important",
        // color:'#525f7f !important',
        fontWeight:'bold !important',
        fontSize:'15px',
        background:'#5cb85c !important',
        color:'white',
    },
    tablecontainer:{
        boxShadow:'none !important',
    },
    textInput : {
        padding: '20px',
        '& .MuiOutlinedInput-notchedOutline': {
            border: '1px solid #b97df0',
        },
    },
    spanInfoIcons : {
        fontSize: '16px', 
        paddingTop: '0px !important', 
        paddingLeft: '1px',
        paddingRight: '2px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px !important', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanIcons : {
        fontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanLoc : {
        ontSize: '16px', 
        paddingTop: '5px !important', 
        paddingLeft: '6px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        borderRadius: '2px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    uploadBtn : {
        border:'1px solid #b97df0 !important',
        borderRadius: '7px !important',
        width: '159px !important',
        fontSize: '11px !important',
        color: '#7009ab !important',
        fontWeight: '600 !important',
            '&:hover' : {
                backgroundColor: '#7009ab !important',
                color: '#fff !important',
            },
    },
    tableHd : {
        backgroundColor: '#7009ab !important',
        fontSize: '20px !important',
        color: '#fff !important',
    },
    container_more: {
        // marginTop: '20px',
        // marginBottom: '10px',
        justifyContent: 'center'
    },
}